annotations:
  category: LogManagement
  licenses: Apache-2.0
apiVersion: v2
appVersion: 8.7.1
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Logstash is an open source data processing engine. It ingests data from
  multiple sources, processes it, and sends the output to final destination in real-time.
  It is a core component of the ELK stack.
home: https://github.com/bitnami/charts/tree/main/bitnami/logstash
icon: https://bitnami.com/assets/stacks/logstash/img/logstash-stack-220x234.png
keywords:
- logstash
- logging
- elk
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: logstash
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/logstash
- https://www.elastic.co/products/logstash
version: 5.3.2
